# Copyright (C) 2020 By Ameng Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci-app-DeviceReboot
LUCI_PKGARCH:=all
PKG_RELEASE:=201200328

include ../../luci.mkuci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

